### ISSUE TITLE
[RFE] Extract MiqPglogical functionality into this gem where appropriate

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/pg-pglogical#4]
It would be nice to have some higher level API than just a wrapper around the stored procs.

The [MiqPglogical](https://github.com/ManageIQ/manageiq/blob/master/lib/miq_pglogical.rb) class is mostly those types of methods. They be extracted and added to this gem where it feels like they would be generally useful.

**Comment by chessbyte** [comment]
@carbonin Is this still a valid RFE?

**Comment by carbonin** [comment]
I don't think so. This gem actually isn't in use since the switch to built-in logical replication so I don't think it's worth considering RFEs.

**Comment by chessbyte** [comment]
@carbonin should we archive this repo then? /cc @Fryguy

**Comment by Fryguy** [comment]
Can't archive yet cause it's used for old versions still.

Actually when did we switch to built in logical replication?

**Comment by carbonin** [comment]
Here https://github.com/ManageIQ/manageiq/pull/18686

So Ivanchuk?
